services:
   postgres:
     image: postgres:15
     container_name: workout_postgres
     restart: always
     environment:
       POSTGRES_USER: workout_user
       POSTGRES_PASSWORD: workout_pass
       POSTGRES_DB: workout_db
     ports:
       - "5432:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: